### ISSUE TITLE
retentionPeriod & synchronous not able to set

### ISSUE THREAD

**Issue by subhajit1997** [kdgregory/log4j-aws-appenders#141]
ERROR:
log4j:WARN No such property [retentionPeriod] in com.kdgregory.log4j.aws.CloudWatchAppender.
log4j:WARN No such property [synchronous] in com.kdgregory.log4j.aws.CloudWatchAppender.

log4j.properties file :
log4j.rootLogger=INFO, console ,cloudwatch

log4j.logger.com.kdgregory=INFO, cloudwatch
log4j.additivity.com.amazonaws=true
log4j.additivity.org.apache.http=true
log4j.additivity.com.kdgregory=true
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d [%t] %-5p %c %x - %m%n

log4j.appender.cloudwatch=com.kdgregory.log4j.aws.CloudWatchAppender
log4j.appender.cloudwatch.layout=org.apache.log4j.PatternLayout
log4j.appender.cloudwatch.layout.ConversionPattern=%d [%t] %-5p %c %x - %m%n

log4j.appender.cloudwatch.logGroup=${CLOUDWATCH_LOG_GROUP}
log4j.appender.cloudwatch.logStream=${CLOUDWATCH_LOG_STREAM}
log4j.appender.cloudwatch.retentionPeriod=3
log4j.appender.cloudwatch.synchronous=true
log4j.logger.org.apache.http=INFO
log4j.logger.com.amazonaws=INFO

log4j.root.priority=INFO
log4j.root.appender-ref=MyDailyRollingFileAppender
log4j.debug=true

**Comment by kdgregory** [comment]
@subhajit1997 - what version are you using? `retentionPeriod` was added in 2.2.1, and `synchronous` was added in 2.2.0.

I've verified that these configuration parameters work with both 3.0.0 (the most recent version, released this week) and 2.4.1 (the previous version), copying your configuration.

However, there's one problem with your configuration: `${CLOUDWATCH_LOG_GROUP}` and `${CLOUDWATCH_LOG_STREAM}` are not supported. I'm assuming that you're referencing environment variables, so the correct syntax for this library is `{env:CLOUDWATCH_LOG_GROUP}`.

This also makes me wonder if you're actually intending to use Log4J 2.x. If yes, then you need to pick the appropriate appender.

Lastly, I do not recommend using `synchronous` unless you're running in a Lambda, where the background writer thread may not be able to execute. It adds a significant penalty to every logging request.

**Comment by subhajit1997** [comment]
thanks earlier i was using version:1.3.0
i have updated to version 3.0.0 for com.kdgregory.logging 
and  <artifactId>aws-sdk-java</artifactId> i am using version 2.10.91
and <artifactId>log4j</artifactId> version: 1.2.17
but now getting below error

**log4j:ERROR CloudWatchAppender(cloudwatch): exception while initializing writer
java.lang.IllegalArgumentException: no implementation class for com.kdgregory.logging.aws.facade.CloudWatchFacade** 
	**at com.kdgregory.logging.aws.facade.FacadeFactory.findImplementationClass(FacadeFactory.java:91)
	at com.kdgregory.logging.aws.facade.FacadeFactory.createFacade(FacadeFactory.java:38)
	at com.kdgregory.logging.aws.cloudwatch.CloudWatchWriterFactory.newLogWriter(CloudWatchWriterFactory.java:40)
	at com.kdgregory.logging.aws.cloudwatch.CloudWatchWriterFactory.newLogWriter(CloudWatchWriterFactory.java:28)
	at com.kdgregory.log4j.aws.internal.AbstractAppender.startWriter(AbstractAppender.java:502)
	at com.kdgregory.log4j.aws.internal.AbstractAppender.initialize(AbstractAppender.java:473)
	at com.kdgregory.log4j.aws.internal.AbstractAppender.append(AbstractAppender.java:393)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.info(Category.java:666)
......
log4j:ERROR CloudWatchAppender(cloudwatch): unable to append event
java.lang.NullPointerException
....**
what could cause this issue could you please help

**Comment by subhajit1997** [comment]
i thought of using synchronous as currently the last few logs are not able to be appended into cloudwtach logGroup and before appending completes java application is exiting and i have requirement of not using wait stage .
Could you suggest of a better way of getting all logs before application completes?

**Comment by kdgregory** [comment]
The error ("no implementation class") is because you need to include two JARs now, instead of just one. The first is the appenders JAR for your logging framework, the second is the "facade" JAR to support the AWS SDK that you're using. The top-level README contains links that will show you the latest versions of these JARs on Maven Central.

Re shutting down: recent versions include a shutdown hook that will ensure that any queued events are written to the destination. So you shouldn't need synchronous mode.

**Comment by subhajit1997** [comment]
thanks you very much

**Comment by longxiangdai** [comment]
Hey, I encountered the same error after upgrading the appenders package from 2.3 to 3.2 recently. What steps did you take to fix the problem?

2024-01-03 19:52:41,613 UTC ERROR StatusConsoleListener exception while initializing writer
2024-01-03 19:52:41,613 UTC  java.lang.IllegalArgumentException: no implementation class for com.kdgregory.logging.aws.facade.CloudWatchFacade
2024-01-03 19:52:41,613 UTC 	at com.kdgregory.logging.aws.facade.FacadeFactory.findImplementationClass(FacadeFactory.java:91)
2024-01-03 19:52:41,613 UTC 	at com.kdgregory.logging.aws.facade.FacadeFactory.createFacade(FacadeFactory.java:38)
2024-01-03 19:52:41,613 UTC 	at com.kdgregory.logging.aws.cloudwatch.CloudWatchWriterFactory.newLogWriter(CloudWatchWriterFactory.java:40)
2024-01-03 19:52:41,613 UTC 	at com.kdgregory.logging.aws.cloudwatch.CloudWatchWriterFactory.newLogWriter(CloudWatchWriterFactory.java:28)
2024-01-03 19:52:41,613 UTC 	at com.kdgregory.log4j2.aws.internal.AbstractAppender.startWriter(AbstractAppender.java:266)
2024-01-03 19:52:41,613 UTC 	at com.kdgregory.log4j2.aws.internal.AbstractAppender.start(AbstractAppender.java:163)
2024-01-03 19:52:41,613 UTC 	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:320)
2024-01-03 19:52:41,613 UTC 	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:621)
2024-01-03 19:52:41,613 UTC 	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:694)
2024-01-03 19:52:41,613 UTC 	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:711)
2024-01-03 19:52:41,613 UTC 	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
2024-01-03 19:52:41,613 UTC 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
2024-01-03 19:52:41,613 UTC 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
2024-01-03 19:52:41,613 UTC 	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
2024-01-03 19:52:41,613 UTC 	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
2024-01-03 19:52:41,613 UTC 	at amazon.platform.config.AppConfig.<clinit>(AppConfig.java:154)

**Comment by kdgregory** [comment]
@longxiangdai - the answer (which is visible above your comment) is that you need two JARs for version 3.x. See the examples for more info.
