### ISSUE TITLE
unexpected exception:  com.amazonaws.AbortedException

### ISSUE THREAD

**Issue by kaliman** [kdgregory/log4j-aws-appenders#183]
Hi, I am using v3.1.1 with AWS v1.12.455 and Log4j2 v2.17.1

When trying to send to CloudWatch, the message can be sent, but there is the following exception after the lambda finishes the execution:

```java
2023-05-11T20:01:08.609Z	2023-05-11 20:01:08,608 com-kdgregory-aws-logwriter-log4j2-cloudwatch-1 ERROR failed to send: retrieveSequenceToken()(myloggroup,myloggroup-20230511_20): unexpected exception: com.amazonaws.AbortedException:
2023-05-11T20:01:08.609Z	at com.amazonaws.internal.SdkFilterInputStream.abortIfNeeded(SdkFilterInputStream.java:61)
2023-05-11T20:01:08.609Z	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:89)
2023-05-11T20:01:08.609Z	at org.apache.http.entity.InputStreamEntity.writeTo(InputStreamEntity.java:140)
2023-05-11T20:01:08.609Z	at com.amazonaws.http.RepeatableInputStreamRequestEntity.writeTo(RepeatableInputStreamRequestEntity.java:160)
2023-05-11T20:01:08.609Z	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
2023-05-11T20:01:08.609Z	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:152)
2023-05-11T20:01:08.609Z	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
2023-05-11T20:01:08.609Z	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doSendRequest(SdkHttpRequestExecutor.java:63)
2023-05-11T20:01:08.609Z	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
2023-05-11T20:01:08.609Z	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
2023-05-11T20:01:08.609Z	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
2023-05-11T20:01:08.609Z	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
2023-05-11T20:01:08.609Z	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
2023-05-11T20:01:08.609Z	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
2023-05-11T20:01:08.609Z	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
2023-05-11T20:01:08.609Z	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1346)
2023-05-11T20:01:08.609Z	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
2023-05-11T20:01:08.609Z	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
2023-05-11T20:01:08.609Z	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
2023-05-11T20:01:08.609Z	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
2023-05-11T20:01:08.609Z	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
2023-05-11T20:01:08.609Z	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
2023-05-11T20:01:08.609Z	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
2023-05-11T20:01:08.609Z	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
2023-05-11T20:01:08.609Z	at com.amazonaws.services.logs.AWSLogsClient.doInvoke(AWSLogsClient.java:4000)
2023-05-11T20:01:08.609Z	at com.amazonaws.services.logs.AWSLogsClient.invoke(AWSLogsClient.java:3967)
2023-05-11T20:01:08.609Z	at com.amazonaws.services.logs.AWSLogsClient.invoke(AWSLogsClient.java:3956)
2023-05-11T20:01:08.609Z	at com.amazonaws.services.logs.AWSLogsClient.executeDescribeLogStreams(AWSLogsClient.java:1647)
2023-05-11T20:01:08.609Z	at com.amazonaws.services.logs.AWSLogsClient.describeLogStreams(AWSLogsClient.java:1616)
2023-05-11T20:01:08.609Z	at com.kdgregory.logging.aws.facade.v1.CloudWatchFacadeImpl.internalFindLogStream(CloudWatchFacadeImpl.java:331)
2023-05-11T20:01:08.609Z	at com.kdgregory.logging.aws.facade.v1.CloudWatchFacadeImpl.retrieveSequenceToken(CloudWatchFacadeImpl.java:180)
2023-05-11T20:01:08.609Z	at com.kdgregory.logging.aws.cloudwatch.CloudWatchLogWriter.retrieveSequenceToken(CloudWatchLogWriter.java:284)
2023-05-11T20:01:08.609Z	at com.kdgregory.logging.aws.cloudwatch.CloudWatchLogWriter.lambda$sendBatch$0(CloudWatchLogWriter.java:141)
2023-05-11T20:01:08.609Z	at com.kdgregory.logging.common.util.RetryManager2.invoke(RetryManager2.java:99)
2023-05-11T20:01:08.609Z	at com.kdgregory.logging.common.util.RetryManager2.invoke(RetryManager2.java:128)
2023-05-11T20:01:08.609Z	at com.kdgregory.logging.aws.cloudwatch.CloudWatchLogWriter.sendBatch(CloudWatchLogWriter.java:137)
2023-05-11T20:01:08.609Z	at com.kdgregory.logging.aws.internal.AbstractLogWriter.processBatch(AbstractLogWriter.java:326)
2023-05-11T20:01:08.609Z	at com.kdgregory.logging.aws.internal.AbstractLogWriter.run(AbstractLogWriter.java:141)
2023-05-11T20:01:08.609Z	at java.lang.Thread.run(Thread.java:750)
```

**Comment by kdgregory** [comment]
@kaliman 

> after the lambda finishes the execution

Showing the complete Lambda log message would be helpful, but I suspect that what's happening is that the Lambda execution context is frozen in the middle of making a request, and then the request fails once it thaws for the next invocation. This happens because the log-writer uses a background thread; you can disable that thread using the `synchronous` configuration parameter.

If you're not using version 3.1.1, released earlier this week, you should upgrade. Earlier versions would let some exceptions escape the log-writer, to be caught be the thread's uncaught exception handler. It wouldn't cause the log-writer to shut down, but would lose a batch.

With that said, I recommend using the built-in logging framework with Lambda rather than this library.

**Comment by kaliman** [comment]
Hi @kdgregory!

I am using v3.1.1.

The following is log4j2.xml, I am trying to send a package to another log group, is it feasible with the built-in logging framework with Lambda?

```java
<Configuration status="INFO">
	<Appenders>
		<Lambda name="Lambda">
			<JsonTemplateLayout eventTemplateUri="classpath:JSONTemplateLayout.json"/>
		</Lambda>

		<CloudWatchAppender name="MyLogGroupAppender">
			<logGroup>myloggroup</logGroup>
			<logStream>myloggroup-${date:yyyyMMdd_HH}</logStream>
			<JsonTemplateLayout eventTemplateUri="classpath:JSONTemplateLayout.json"/>
		</CloudWatchAppender>
	</Appenders>

	<Loggers>
		<logger name="com.co.utils" level="INFO" additivity="false">
			<AppenderRef ref="MyLogGroupAppender"/>
		</logger>
		<Root level="DEBUG">
			<AppenderRef ref="Lambda"/>
		</Root>
	</Loggers>
</Configuration>
```

**Comment by kdgregory** [comment]
@kaliman 

> I am trying to send a package to another log group, is it feasible with the built-in logging framework with Lambda

As far as I know, there's no way to change the `/aws/lambda/XXX` default log group. So if you really want to use a different log group, and use this appender, then I think you'll have to enable synchronous mode. Add this to the appender config:

```
<synchronous>true</synchronous>
```

This will cause the logger library to write each message to CloudWatch as it's logged, which will slow down whatever is doing the logging. Depending on how much logging you're doing, that may be a problem. The SDK should at least keep the connection open between calls, so you're not paying to establish it each time.

If you're using the V2 Java SDK, then AWS [recommends their CRT client](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/http-configuration.html#http-clients-recommend) when running in Lambda. I don't think this will provide any performance benefit, because all of the appender's calls are synchronous (and wouldn't benefit from async calls). But it might be worthwhile trying if you have performance issues.

**Comment by kaliman** [comment]
Thanks @kdgregory !
