### ISSUE TITLE
error during putEvent to cloudwatch for error logs

### ISSUE THREAD

**Issue by monikadr** [kdgregory/log4j-aws-appenders#189]
Hello,

I am using below configurations:
    implementation 'com.kdgregory.logging:log4j2-aws-appenders:3.1.1'
    implementation 'com.kdgregory.logging:aws-facade-v2:3.1.1'
    implementation 'software.amazon.awssdk:cloudwatchlogs:2.18.32'
    implementation 'software.amazon.awssdk:iam:2.18.32'

All the info and debug messages are being sent to cloudwatch successfully, but error logs are not
below is the error I see 
2023-07-03 14:52:44,532 com-kdgregory-aws-logwriter-log4j2-cloudwatch-1 ERROR failed to send: putEvents(*************): unexpected exception: null software.amazon.awssdk.core.exception.AbortedException
	at software.amazon.awssdk.core.exception.AbortedException$BuilderImpl.build(AbortedException.java:93)
	at software.amazon.awssdk.core.io.SdkFilterInputStream.abortIfNeeded(SdkFilterInputStream.java:45)
	at software.amazon.awssdk.core.io.SdkFilterInputStream.markSupported(SdkFilterInputStream.java:101)
	at software.amazon.awssdk.http.apache.internal.RepeatableInputStreamRequestEntity.isRepeatable(RepeatableInputStreamRequestEntity.java:128)
	at org.apache.http.impl.execchain.RequestEntityProxy.enhance(RequestEntityProxy.java:47)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:171)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at software.amazon.awssdk.http.apache.internal.impl.ApacheSdkHttpClient.execute(ApacheSdkHttpClient.java:72)
	at software.amazon.awssdk.http.apache.ApacheHttpClient.execute(ApacheHttpClient.java:254)
	at software.amazon.awssdk.http.apache.ApacheHttpClient.access$500(ApacheHttpClient.java:104)
	at software.amazon.awssdk.http.apache.ApacheHttpClient$1.call(ApacheHttpClient.java:231)
	at software.amazon.awssdk.http.apache.ApacheHttpClient$1.call(ApacheHttpClient.java:228)
	at software.amazon.awssdk.core.internal.util.MetricUtils.measureDurationUnsafe(MetricUtils.java:63)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.executeHttpRequest(MakeHttpRequestStage.java:77)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:56)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.cloudwatchlogs.DefaultCloudWatchLogsClient.putLogEvents(DefaultCloudWatchLogsClient.java:3249)
	at com.kdgregory.logging.aws.facade.v2.CloudWatchFacadeImpl.putEvents(CloudWatchFacadeImpl.java:210)
	at com.kdgregory.logging.aws.cloudwatch.CloudWatchLogWriter.lambda$sendBatch$0(CloudWatchLogWriter.java:141)
	at com.kdgregory.logging.common.util.RetryManager2.invoke(RetryManager2.java:99)
	at com.kdgregory.logging.common.util.RetryManager2.invoke(RetryManager2.java:128)
	at com.kdgregory.logging.aws.cloudwatch.CloudWatchLogWriter.sendBatch(CloudWatchLogWriter.java:137)
	at com.kdgregory.logging.aws.internal.AbstractLogWriter.processBatch(AbstractLogWriter.java:326)
	at com.kdgregory.logging.aws.internal.AbstractLogWriter.run(AbstractLogWriter.java:141)

Could you please point me to the right directory if I am missing anything
Error logs where being sent successfully before, but it stopped working recently

**Comment by kdgregory** [comment]
I would look at your logging configuration. By the time the log message gets to the appender, there is no difference between error, info, or debug.

As for the error you're seeing: it does not affect sending events. When a batch fails, the events are requeued and will be sent in a subsequent attempt. The particular exception is reported as "unexpected" because it's not  [documented](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html#API_PutLogEvents_Errors) as an error that the `PutLogEvents` API call might return.

I recognize that you (and others) don't want to see this message in your logging output, so will release a patch for it. However, I'm very busy for the next several weeks, so don't expect to be able to do that until August.

**Comment by kdgregory** [comment]
Fixing this as part of release 3.2.0.
