### ISSUE TITLE
an exception that is getting thrown once in a while

### ISSUE THREAD

**Issue by tchaikovsky00000** [kdgregory/log4j-aws-appenders#190]
The Log4j2 cw appender seems not to be working due to the error below...

```
2023-07-26 22:53:42,017 main ERROR Could not create plugin of type class com.kdgregory.log4j2.aws.CloudWatchAppender for element CloudWatchAppender: java.lang.NoSuchFieldError: DEFAULT_DISCARD_ACTION java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.createBuilder(PluginBuilder.java:158)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:120)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1014)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:954)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:946)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:560)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:245)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:292)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:579)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:651)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:668)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:138)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:45)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:48)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
        at org.apache.spark.internal.Logging.log(Logging.scala:50)
        at org.apache.spark.internal.Logging.log$(Logging.scala:47)
        at org.apache.spark.deploy.SparkSubmit.log(SparkSubmit.scala:75)
        at org.apache.spark.internal.Logging.initializeLogging(Logging.scala:175)
        at org.apache.spark.internal.Logging.initializeLogIfNecessary(Logging.scala:111)
        at org.apache.spark.internal.Logging.initializeLogIfNecessary$(Logging.scala:105)
        at org.apache.spark.deploy.SparkSubmit.initializeLogIfNecessary(SparkSubmit.scala:75)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:83)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.NoSuchFieldError: DEFAULT_DISCARD_ACTION
        at com.kdgregory.log4j2.aws.internal.AbstractAppenderBuilder.<init>(AbstractAppenderBuilder.java:163)
        at com.kdgregory.log4j2.aws.CloudWatchAppender$CloudWatchAppenderBuilder.<init>(CloudWatchAppender.java:206)
        at com.kdgregory.log4j2.aws.CloudWatchAppender.newBuilder(CloudWatchAppender.java:198)
        ... 35 more

```

P.S. I'm having the following jars in my classpath (can't actually work with maven, as I'm running on Apache-Spark, which has log4j2 built-in): 

```
- aws-facade-v2-3.1.2.jar
- log4j2-aws-appenders-3.1.2.jar
- logwriters-3.1.2.jar
- aws-shared-2.4.1.jar
- kdgcommons-1.0.16.jar

```
And actually also tried the same combination by replacing the facade jar from v2 to v1. And got the same behavior...

**Comment by tchaikovsky00000** [comment]
```
In my log4j2.xml:

...
<Appenders>
....
    <CloudWatchAppender name="CLOUDWATCH">
        <logGroup>foo</logGroup>
        <logStream>bar-log4j2-cw-appender-{date}-{hostname}-${awslogs:pid}</logStream>
        <PatternLayout pattern="${sys:PATTERN}" />
    </CloudWatchAppender>
...
</Appenders>
...
    <Root level="${sys:root.log.level}">
        <AppenderRef ref="CLOUDWATCH"  level="${sys:root.log.level}"/>
    </Root>
...
```

**Comment by kdgregory** [comment]
You shouldn't be using `aws-shared-2.4.1.jar`: it is from a previous release of the library. It's likely that, depending on how the JARs are loaded on the classpath, the 3.1.2 logging classes are trying (and failing) to load classes from the 2.4.1 shared library.

You also don't need `kdgcommons` unless you're using it for other purposes. Please take a look at the Log4J2 example, which shows all of the JARs that you'll need to run this library with Log4J2 (and no extras).
