### ISSUE TITLE
CloudWatchAppender: deleting logstream while appender is running does not invoke uncaught exception handler

### ISSUE THREAD

**Issue by kdgregory** [kdgregory/log4j-aws-appenders#46]
Instead, it reports a NullPointerException and continues with the same writer:
```
log4j:ERROR failed to send batch
java.lang.NullPointerException
	at com.kdgregory.log4j.aws.internal.cloudwatch.CloudWatchLogWriter.attemptToSend(CloudWatchLogWriter.java:160)
	at com.kdgregory.log4j.aws.internal.cloudwatch.CloudWatchLogWriter.processBatch(CloudWatchLogWriter.java:122)
	at com.kdgregory.log4j.aws.internal.shared.AbstractLogWriter.run(AbstractLogWriter.java:178)
	at java.lang.Thread.run(Thread.java:748)
```

This isn't a major problem, assuming that the appender is configured to discard messages, but is not the desired behavior.

**Comment by kdgregory** [comment]
Similar issue for `KinesisAppender`:

```
log4j:ERROR failed to send batch after 3 retries
com.amazonaws.services.kinesis.model.ResourceNotFoundException: Stream AppenderExample under account 717623742438 not found. (Service: AmazonKinesis; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 0f69b6f1-e395-4c76-82c6-d2a5c3888351)
...
	at com.amazonaws.services.kinesis.AmazonKinesisClient.putRecords(AmazonKinesisClient.java:1673)
	at com.kdgregory.log4j.aws.internal.kinesis.KinesisLogWriter.attemptToSend(KinesisLogWriter.java:308)
```

**Comment by kdgregory** [comment]
After giving this some more thought, I'm only planning to change only the CloudWatch appender.

The primary reason is that, for Kinesis or SNS, I expect only a single, long-lived destination, shared b all applications, and created by the user in the first place. If s/he deletes it, s/he can see the error and re-create it.

By comparison, each application would normally write to its own CloudWatch group/stream, creates the stream itself, and probably uses substitution variables to identify that group/stream. So I think that the natural behavior is "something went wrong, try again."

**Comment by kdgregory** [comment]
After a little more time spent with the code, the uncaught exception handler is the wrong approach for this (for one thing, it shuts down the appender entirely). Better is to handle it within the log writer: try to retrieve the logstream and call `ensureDestinationAvailable()` if it's not there.

This also simplifies the handling of putRecords(): if it throws then we'll retry the batch, and during the retry attempt to re-create the stream. If that fails (probably due to permissions) it's probably a user-fixable problem, so we'll keep trying.
