### ISSUE TITLE
InvalidSequenceTokenException

### ISSUE THREAD

**Issue by austince** [kdgregory/log4j-aws-appenders#59]
Hi, I'm seeing a few instances of this error running on an EMR cluster. Logging to Cloudwatch seems to be working great, so just wanted to make sure this isn't something to worry about.

Thank you!

```
com.amazonaws.services.logs.model.InvalidSequenceTokenException: The given sequenceToken is invalid. The next expected sequenceToken is: 49590293515121184143516241009459514993483551644565275730 (Service: AWSLogs; Status Code: 400; Error Code: InvalidSequenceTokenException; Request ID: beb5c305-ecec-11e8-8b3d-eb0eed77c973)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1658)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1322)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1072)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:515)
	at com.amazonaws.services.logs.AWSLogsClient.doInvoke(AWSLogsClient.java:2624)
	at com.amazonaws.services.logs.AWSLogsClient.invoke(AWSLogsClient.java:2593)
	at com.amazonaws.services.logs.AWSLogsClient.invoke(AWSLogsClient.java:2582)
	at com.amazonaws.services.logs.AWSLogsClient.executePutLogEvents(AWSLogsClient.java:2084)
	at com.amazonaws.services.logs.AWSLogsClient.putLogEvents(AWSLogsClient.java:2055)
	at com.kdgregory.log4j.aws.internal.cloudwatch.CloudWatchLogWriter.attemptToSend(CloudWatchLogWriter.java:169)
	at com.kdgregory.log4j.aws.internal.cloudwatch.CloudWatchLogWriter.processBatch(CloudWatchLogWriter.java:122)
	at com.kdgregory.log4j.aws.internal.shared.AbstractLogWriter.run(AbstractLogWriter.java:180)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by austince** [comment]
@kdgregory - the batch delay should be the default, though there may be a large number of processes running; I'm not quite sure as Apache Flink / Apache YARN manage that. And yes, we were able to get at least partial success with EMR, as our Flink App logs to Cloudwatch, but have left the Resource / Job managers to use the built-in S3 log solution. So we're halfway-happy, thank you!

**Comment by kdgregory** [comment]
@austince - I've made a change that silently retries when the appender receives this error. It will be going out in the 2.0.1 release, which should happen this upcoming weekend (if not earlier).

After giving some more thought to your situation, I think the errors are happening because all of the processes are starting at the same time, which means that they'll all write batches at (approximately) the same time. This change, by introducing a delay between retries, will cause the appenders to drift apart, so in the long term they will all write at different times and should not get the error.

**Comment by kdgregory** [comment]
@austince - 2.0.1 is now available from Maven Central.

I also [added some documentation](https://github.com/kdgregory/log4j-aws-appenders/blob/master/docs/cloudwatch.md#invalidsequencetokenexception-and-logstream-throttling) on writer races and throttling in general.

**Comment by austince** [comment]
Thanks so much @kdgregory! Will look into upgrading in the coming weeks.

**Comment by austince** [comment]
@kdgregory, just saw a `DataAlreadyAcceptedException` as well. Is this an instance of the same race condition?


```
com.amazonaws.services.logs.model.DataAlreadyAcceptedException: The given batch of log events has already been accepted. The next batch can be sent with sequenceToken: <TOKEN> (Service: AWSLogs; Status Code: 400; Error Code: DataAlreadyAcceptedException; Request ID: 2ebd2402-f999-11e8-815b-ab79b77e9353)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1658)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1322)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1072)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:515)
	at com.amazonaws.services.logs.AWSLogsClient.doInvoke(AWSLogsClient.java:2624)
	at com.amazonaws.services.logs.AWSLogsClient.invoke(AWSLogsClient.java:2593)
	at com.amazonaws.services.logs.AWSLogsClient.invoke(AWSLogsClient.java:2582)
	at com.amazonaws.services.logs.AWSLogsClient.executePutLogEvents(AWSLogsClient.java:2084)
	at com.amazonaws.services.logs.AWSLogsClient.putLogEvents(AWSLogsClient.java:2055)
	at com.kdgregory.log4j.aws.internal.cloudwatch.CloudWatchLogWriter.attemptToSend(CloudWatchLogWriter.java:169)
	at com.kdgregory.log4j.aws.internal.cloudwatch.CloudWatchLogWriter.processBatch(CloudWatchLogWriter.java:122)
	at com.kdgregory.log4j.aws.internal.shared.AbstractLogWriter.run(AbstractLogWriter.java:180)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by JustAnotherContributor** [comment]
@austince, do you have any instructions for how you got the CloudWatchAppender working in EMR? I got EMR recognising my log4j.xml or log4j.properties file by uploading them to an S3 bucket and then using the following arguments to the "aws emr add-step" command but as per #163 I get a ClassNotFoundException when log4j attempts to load the appender:
`--files,s3a://<bucket>/<folder>/log4j.properties,--conf,spark.driver.extraJavaOptions=-Dlog4j.configuration=file:log4j.properties,--conf,spark.executor.extraJavaOptions=-Dlog4j.configuration=file:log4j.properties`

**Comment by austince** [comment]
Unfortunately, this was so long ago that I no longer have my config/ know what worked. These days, I'm running Flink elsewhere (and having a much better experience than with Spark :)).
