### ISSUE TITLE
Must include SDK JARs for all clients, even if just using one destination

### ISSUE THREAD

**Issue by kdgregory** [kdgregory/log4j-aws-appenders#71]
[DefaultClientFactory](https://github.com/kdgregory/log4j-aws-appenders/blob/master/aws-shared/src/main/java/com/kdgregory/logging/aws/common/DefaultClientFactory.java) compares the desired client class against supported class objects (eg, `AWSLogs.class`). This requires the class objects to be loaded. If you do not include the relevant SDK JAR you will get a message like this:
```
com/amazonaws/services/kinesis/AmazonKinesisClient: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: com/amazonaws/services/kinesis/AmazonKinesisClient
at com.kdgregory.logging.aws.cloudwatch.CloudWatchWriterFactory.newLogWriter(CloudWatchWriterFactory.java:34)
at com.kdgregory.logging.aws.cloudwatch.CloudWatchWriterFactory.newLogWriter(CloudWatchWriterFactory.java:28)
at com.kdgregory.log4j.aws.internal.AbstractAppender.startWriter(AbstractAppender.java:527)
```

The solution is to get the name of the class and compare against known classnames.

**Comment by kdgregory** [comment]
This will be fixed by this weekend.
